name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  Push:
    runs-on: ubuntu-latest
    if: github.repository == 'CommitCrimes/Marvinet'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Epitech repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.TARGET }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}